# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='names',
            field=models.CharField(default=1, max_length=255, verbose_name='映っているキャラ達'),
            preserve_default=False,
        ),
    ]
